feat: integrate with secret square server api
AboutClan/About pull request #200
Opened 2024-07-30 14:30 UTC by ojj1123

follow up #185 

## TODO
- [ ] API 연동

2024-08-03 21:57 UTC, ojj1123 commented on components/molecules/ImageUploadButton.tsx
> +      toast("free", "이미지는 5개 이하로 추가할 수 있어요.");
문구 변경

2024-08-09 15:11 UTC, ojj1123 commented on components/molecules/ImageUploadButton.tsx
> +    }
@SeungJL 
최대 파일 개수를 제한해줘야 해서 이런 조건문을 넣었습니다!
`maxFiles` 값이 `undefined`라면 개수 제한이 없고, `maxFiles` 값이 있다면 그 값이 최대 파일 개수가 됩니다.

2024-08-09 15:19 UTC, ojj1123 commented on libs/methodHelpers.ts
> +      return axios.put(`${SERVER_URI}/${url}`, { data: body });
put 메서드가 필요해서 추가했어요

2024-08-09 15:21 UTC, ojj1123 commented on pageTemplates/square/SecretSquare/SquareItem.tsx
> +    <Layout href={`/square/secret/${item._id}`}>
시크릿 스퀘어 글 목록마다 링크(href)를 달아주었습니다.

2024-08-09 16:28 UTC, createhb21 commented
혹시 프로젝트에 모듈 import하는거
절대경로 설정이 안되어있어서 상대경로 사용하고 있는건가요?

2024-08-09 16:28 UTC, createhb21 requested changes

2024-08-09 16:28 UTC, createhb21 commented on components/molecules/ImageUploadButton.tsx
> +  maxFiles,
maxFileNum 처럼 좀 더 시맨틱하게 작성하면 어떨까요 👍

2024-08-09 16:28 UTC, createhb21 commented on hooks/secretSquare/queries.ts
> +  useQuery<SecretSquareListResponse, AxiosError, SecretSquareListResponse>(
리액트쿼리 라이브러리 자체에서 타입 추론 되지않나요?!

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SecretSquare/SecretSquareComments.tsx
> +interface SecretSquareCommentsProps {}
의도하신 인터페이스 선언인가요 🧐

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SecretSquare/SecretSquareComments.tsx
> +  const { data } = useFeedsQuery("group", 110, null, null);
("group", 110, null, null) 
보다 좀 더 가독성 좋게 작성하면 좋을 것 같아용

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SecretSquare/SecretSquareComments.tsx
> +    setCommentArr(comments);
comments 타입은 UserCommentProps[]로 명시되어있는데
위의 코드라면 undefined가 되버릴수도있을것같아요 :)

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SecretSquare/SecretSquareComments.tsx
> +            setCommentArr={setCommentArr}
setState함수를 props 바로 넘기는것보다 핸들러함수를 만들어서 useCallback으로 감싸서 넘겨주는게 더 좋다고 생각해요 💡

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SecretSquare/SquareItem.tsx
> +        sx={{
텍스트 관련해서 Line Clamp 속성때문에 인라인으로 사용하는게 중복될거라면
공용으로 따로 커스텀Text 컴포넌트를 만들거나 props로 옵셔날하게 받는 방법도 있을것같아요
꼭 필요한것이라기보단 시간이 충분하다면 해볼만한 것 같아요

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SecretSquare/writing/PollCreatorDrawer.tsx
>              onClick={async () => {
인라인으로 하기보다 따로 빼는게 좋지않을까요!

2024-08-09 16:28 UTC, createhb21 commented on pageTemplates/square/SquareSecretSection.tsx
> +          (data.squareList.length === 0 ? (
const isEmpty = !squareList.length;

선언하고 사용하는건 어떨까요?

2024-08-11 13:50 UTC, ojj1123 commented on pageTemplates/square/SecretSquare/writing/PollCreatorDrawer.tsx
>              onClick={async () => {
[23b218a](https://github.com/AboutClan/About/pull/200/commits/23b218a68ddf3dd08e30dd429da0bc5ba00f61c4)

반영했습니다 :)

2024-08-12 16:58 UTC, merged